CREATE TABLE IF NOT EXISTS FILM
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100) NOT NULL,
    description  varchar(200),
    release_date date    NOT NULL,
    duration     integer NOT NULL,
    rating_id    integer NOT NULL,
    CONSTRAINT name_not_blank CHECK (name <> ''),
    CONSTRAINT positive_duration CHECK (duration > 0)
);

CREATE TABLE IF NOT EXISTS FILM_LIKE
(
    film_id integer NOT NULL,
    user_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRE
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    film_id  integer NOT NULL,
    genre_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS RATING
(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(50) NOT NULL,
    CONSTRAINT rating_name_values CHECK (name IN ('G', 'PG', 'PG-13', 'R', 'NC-17'))
);

CREATE TABLE IF NOT EXISTS USERS
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(320) NOT NULL,
    login    varchar(100) NOT NULL,
    name     varchar(100) NOT NULL,
    birthday date    NOT NULL,
    CONSTRAINT email_not_blank CHECK (email <> '')
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP
(
    user_id              integer NOT NULL,
    friend_id            integer NOT NULL,
    friendship_status_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP_STATUS
(
    friendship_status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status               varchar NOT NULL,
    CONSTRAINT status_values CHECK(status IN ('NOT_CONFIRMED', 'CONFIRMED'))
);

CREATE TABLE IF NOT EXISTS DIRECTOR
(
    director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(100) NOT NULL,
    CONSTRAINT director_name_not_blank CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS FILM_DIRECTOR
(
    film_id     integer NOT NULL,
    director_id integer NOT NULL,
    PRIMARY KEY (film_id, director_id)
);

ALTER TABLE film ADD FOREIGN KEY (rating_id) REFERENCES RATING (rating_id);

ALTER TABLE film_like ADD FOREIGN KEY (film_id) REFERENCES FILM (film_id) ON DELETE CASCADE;

ALTER TABLE film_like ADD FOREIGN KEY (user_id) REFERENCES USERS (user_id) ON DELETE CASCADE;

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES FILM (film_id) ON DELETE CASCADE;

ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES GENRE (genre_id) ON DELETE CASCADE;

ALTER TABLE friendship ADD FOREIGN KEY (user_id) REFERENCES USERS (user_id) ON DELETE CASCADE;

ALTER TABLE friendship ADD FOREIGN KEY (friend_id) REFERENCES USERS (user_id) ON DELETE CASCADE;

ALTER TABLE friendship ADD FOREIGN KEY (friendship_status_id) REFERENCES FRIENDSHIP_STATUS (friendship_status_id);

CREATE INDEX IF NOT EXISTS IDX_FRIENDSHIP ON FRIENDSHIP(user_id, friend_id);

ALTER TABLE FILM_DIRECTOR ADD FOREIGN KEY (film_id) REFERENCES FILM (film_id) ON DELETE CASCADE;

ALTER TABLE FILM_DIRECTOR ADD FOREIGN KEY (director_id) REFERENCES DIRECTOR (director_id) ON DELETE CASCADE;
